apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: config
  namespace: default
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: config
  template:
    metadata:
      labels:
        app: config
        contrail_manager: config
    spec:
      containers:
      - image: docker.io/michaelhenkel/contrail-controller-config-api:5.2.0-dev1
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        imagePullPolicy: Always
        name: api
        readinessProbe:
          httpGet:
            path: /
            port: 8082
        volumeMounts:
        - mountPath: /var/log/contrail
          name: config-logs
      - image: docker.io/michaelhenkel/contrail-controller-config-devicemgr:5.2.0-dev1
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        imagePullPolicy: Always
        name: devicemanager
        volumeMounts:
        - mountPath: /var/log/contrail
          name: config-logs
      - image: docker.io/michaelhenkel/contrail-controller-config-schema:5.2.0-dev1
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        imagePullPolicy: Always
        name: schematransformer
        volumeMounts:
        - mountPath: /var/log/contrail
          name: config-logs
      - image: docker.io/michaelhenkel/contrail-controller-config-svcmonitor:5.2.0-dev1
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        imagePullPolicy: Always
        name: servicemonitor
        volumeMounts:
        - mountPath: /var/log/contrail
          name: config-logs
      - image: docker.io/michaelhenkel/contrail-analytics-api:5.2.0-dev1
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        imagePullPolicy: Always
        name: analyticsapi
        volumeMounts:
        - mountPath: /var/log/contrail
          name: config-logs
      - image: docker.io/michaelhenkel/contrail-analytics-collector:5.2.0-dev1
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        imagePullPolicy: Always
        name: collector
        volumeMounts:
        - mountPath: /var/log/contrail
          name: config-logs
      - image: docker.io/michaelhenkel/contrail-external-redis:5.2.0-dev1
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        imagePullPolicy: Always
        name: redis
        volumeMounts:
        - mountPath: /var/log/contrail
          name: config-logs
        - mountPath: /var/lib/redis
          name: config-data
      - env:
        - name: DOCKER_HOST
          value: unix://mnt/docker.sock
        - name: NODE_TYPE
          value: config
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: docker.io/michaelhenkel/contrail-nodemgr:5.2.0-dev1
        imagePullPolicy: Always
        name: nodemanagerconfig
        volumeMounts:
        - mountPath: /var/log/contrail
          name: config-logs
        - mountPath: /mnt
          name: docker-unix-socket
      - env:
        - name: DOCKER_HOST
          value: unix://mnt/docker.sock
        - name: NODE_TYPE
          value: analytics
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        image: docker.io/michaelhenkel/contrail-nodemgr:5.2.0-dev1
        imagePullPolicy: Always
        name: nodemanageranalytics
        volumeMounts:
        - mountPath: /var/log/contrail
          name: config-logs
        - mountPath: /mnt
          name: docker-unix-socket
      dnsPolicy: ClusterFirst
      hostNetwork: true
      initContainers:
      - command:
        - sh
        - -c
        - until grep ready /tmp/podinfo/pod_labels > /dev/null 2>&1; do sleep 1; done
        env:
        - name: CONTRAIL_STATUS_IMAGE
          value: docker.io/michaelhenkel/contrail-status:5.2.0-dev1
        image: busybox:1.31
        imagePullPolicy: Always
        name: init
        volumeMounts:
        - mountPath: /tmp/podinfo
          name: status
      - env:
        - name: CONTRAIL_STATUS_IMAGE
          value: docker.io/michaelhenkel/contrail-status:5.2.0-dev1
        image: docker.io/michaelhenkel/contrail-node-init:5.2.0-dev1
        imagePullPolicy: Always
        name: nodeinit
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /host/usr/bin
          name: host-usr-local-bin
      nodeSelector:
        node-role.kubernetes.io/master: ""
      tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
      volumes:
      - hostPath:
          path: /var/log/contrail/config
          type: ""
        name: config-logs
      - hostPath:
          path: /var/lib/contrail/config
          type: ""
        name: config-data
      - hostPath:
          path: /var/run
          type: ""
        name: docker-unix-socket
      - hostPath:
          path: /usr/local/bin
          type: ""
        name: host-usr-local-bin
      - downwardAPI:
          defaultMode: 420
          items:
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels
            path: pod_labels
          - fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels
            path: pod_labelsx
        name: status