apiVersion: contrail.juniper.net/v1alpha1
kind: Manager
metadata:
  name: cluster1
  namespace: contrail
spec:
  commonConfiguration:
    hostNetwork: true
    replicas: 3
    keystoneSecretInstance : cluster1-admin-password
    imagePullSecrets:
      - contrail-registry
  services:
    cassandras:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: cassandra1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          containers:
            - name: cassandra
              image: hub.juniper.net/contrail-nightly/contrail-external-cassandra:<CONTRAIL_VERSION>
            - name: init
              image: python:3.8.2-alpine
            - name: init2
              image: hub.juniper.net/contrail-nightly/contrail-external-cassandra:<CONTRAIL_VERSION>
    config:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: config1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
            - name: analyticsapi
              image: hub.juniper.net/contrail-nightly/contrail-analytics-api:<CONTRAIL_VERSION>
            - name: api
              image: hub.juniper.net/contrail-nightly/contrail-controller-config-api:<CONTRAIL_VERSION>
            - name: collector
              image: hub.juniper.net/contrail-nightly/contrail-analytics-collector:<CONTRAIL_VERSION>
            - name: devicemanager
              image: hub.juniper.net/contrail-nightly/contrail-controller-config-devicemgr:<CONTRAIL_VERSION>
            - name: dnsmasq
              image: hub.juniper.net/contrail-nightly/contrail-controller-config-dnsmasq:<CONTRAIL_VERSION>
            - name: init
              image: python:3.8.2-alpine
            - name: init2
              image: busybox:1.31
            - name: nodeinit
              image: hub.juniper.net/contrail-nightly/contrail-node-init:<CONTRAIL_VERSION>
            - name: redis
              image: hub.juniper.net/contrail-nightly/contrail-external-redis:<CONTRAIL_VERSION>
            - name: schematransformer
              image: hub.juniper.net/contrail-nightly/contrail-controller-config-schema:<CONTRAIL_VERSION>
            - name: servicemonitor
              image: hub.juniper.net/contrail-nightly/contrail-controller-config-svcmonitor:<CONTRAIL_VERSION>
            - name: queryengine
              image: hub.juniper.net/contrail-nightly/contrail-analytics-query-engine:<CONTRAIL_VERSION>
            - name: statusmonitor
              image: pitersk/contrail-statusmonitor:<CONTRAIL_VERSION>
          logLevel: SYS_DEBUG
          zookeeperInstance: zookeeper1
    controls:
    - metadata:
        labels:
          contrail_cluster: cluster1
          control_role: master
        name: control1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
            - name: control
              image: hub.juniper.net/contrail-nightly/contrail-controller-control-control:<CONTRAIL_VERSION>
            - name: dns
              image: hub.juniper.net/contrail-nightly/contrail-controller-control-dns:<CONTRAIL_VERSION>
            - name: init
              image: python:3.8.2-alpine
            - name: named
              image: hub.juniper.net/contrail-nightly/contrail-controller-control-named:<CONTRAIL_VERSION>
            - name: nodeinit
              image: hub.juniper.net/contrail-nightly/contrail-node-init:<CONTRAIL_VERSION>
            - name: statusmonitor
              image: pitersk/contrail-statusmonitor:<CONTRAIL_VERSION>
          zookeeperInstance: zookeeper1
    provisionManager:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: provmanager1
      spec:
        commonConfiguration:
          create: true
          replicas: 1
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          containers:
          - name: init
            image: python:3.8.2-alpine
          - name: provisioner
            image: pitersk/contrail-operator-provisioner:<CONTRAIL_VERSION>
    rabbitmq:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: rabbitmq1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          containers:
          - name: init
            image: python:3.8.2-alpine
          - name: rabbitmq
            image: hub.juniper.net/contrail-nightly/contrail-external-rabbitmq:<CONTRAIL_VERSION>
    webui:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: webui1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
            - name: init
              image: python:3.8.2-alpine
            - name: nodeinit
              image: hub.juniper.net/contrail-nightly/contrail-node-init:<CONTRAIL_VERSION>
            - name: redis
              image: hub.juniper.net/contrail-nightly/contrail-external-redis:<CONTRAIL_VERSION>
            - name: webuijob
              image: hub.juniper.net/contrail-nightly/contrail-controller-webui-job:<CONTRAIL_VERSION>
            - name: webuiweb
              image: hub.juniper.net/contrail-nightly/contrail-controller-webui-web:<CONTRAIL_VERSION>
    zookeepers:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: zookeeper1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          containers:
            - name: init
              image: python:3.8.2-alpine
            - name: zookeeper
              image: hub.juniper.net/contrail-nightly/contrail-external-zookeeper:<CONTRAIL_VERSION>
    kubemanagers:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: kubemanager1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          cassandraInstance: cassandra1
          zookeeperInstance: zookeeper1
          containers:
            - name: init
              image: python:3.8.2-alpine
            - name: kubemanager
              image: hub.juniper.net/contrail-nightly/contrail-kubernetes-kube-manager:<CONTRAIL_VERSION>
            - name: nodeinit
              image: hub.juniper.net/contrail-nightly/contrail-node-init:<CONTRAIL_VERSION>
            - name: statusmonitor
              image: pitersk/contrail-statusmonitor:<CONTRAIL_VERSION>
          ipFabricForwarding: false
          ipFabricSnat: true
          kubernetesTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
          useKubeadmConfig: true
          hostNetworkService: true
    vrouters:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: vroutermasternodes
      spec:
        commonConfiguration:
          create: true
          imagePullSecrets:
            - contrail-registry
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          cassandraInstance: cassandra1
          controlInstance: control1
          containers:
            - name: init
              image: python:3.8.2-alpine
            - name: nodeinit
              image: hub.juniper.net/contrail-nightly/contrail-node-init:<CONTRAIL_VERSION>
            - name: vrouteragent
              image: hub.juniper.net/contrail-nightly/contrail-vrouter-agent:<CONTRAIL_VERSION>
            - name: vroutercni
              image: hub.juniper.net/contrail-nightly/contrail-kubernetes-cni-init:<CONTRAIL_VERSION>
            - name: vrouterkernelbuildinit
              image: hub.juniper.net/contrail-nightly/contrail-vrouter-kernel-build-init:<CONTRAIL_VERSION>
            - name: vrouterkernelinit
              image: pitersk/vrouter-kernel-init
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: vrouterworkernodes
      spec:
        commonConfiguration:
          create: true
          imagePullSecrets:
            - contrail-registry
          nodeSelector:
            node-role.kubernetes.io/worker: ""
        serviceConfiguration:
          cassandraInstance: cassandra1
          controlInstance: control1
          containers:
            - name: init
              image: python:3.8.2-alpine
            - name: nodeinit
              image: hub.juniper.net/contrail-nightly/contrail-node-init:<CONTRAIL_VERSION>
            - name: vrouteragent
              image: hub.juniper.net/contrail-nightly/contrail-vrouter-agent:<CONTRAIL_VERSION>
            - name: vroutercni
              image: hub.juniper.net/contrail-nightly/contrail-kubernetes-cni-init:<CONTRAIL_VERSION>
            - name: vrouterkernelbuildinit
              image: hub.juniper.net/contrail-nightly/contrail-vrouter-kernel-build-init:<CONTRAIL_VERSION>
            - name: vrouterkernelinit
              image: pitersk/vrouter-kernel-init
