apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: swiftproxies.contrail.juniper.net
spec:
  group: contrail.juniper.net
  names:
    kind: SwiftProxy
    listKind: SwiftProxyList
    plural: swiftproxies
    singular: swiftproxy
  scope: ""
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: SwiftProxy is the Schema for the swiftproxies API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: SwiftProxySpec defines the desired state of SwiftProxy
          properties:
            serviceConfiguration:
              description: SwiftProxyConfiguration is the Spec for the keystone API.
              properties:
                containers: {}
                credentialsSecretName:
                  type: string
                keystoneInstance:
                  type: string
                keystoneSecretInstance:
                  type: string
                listenPort:
                  type: integer
                memcachedInstance:
                  type: string
                ringPersistentVolumeClaim:
                  type: string
                swiftConfSecretName:
                  type: string
              type: object
          required:
          - serviceConfiguration
          type: object
        status:
          description: SwiftProxyStatus defines the observed state of SwiftProxy
          properties:
            active:
              type: boolean
          required:
          - active
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
