apiVersion: contrail.juniper.net/v1alpha1
kind: ContrailCommand
metadata:
  name: command
spec:
  commonConfiguration:
    activate: true
    create: true
    hostNetwork: true
    tolerations:
      - effect: NoSchedule
        operator: Exists
      - effect: NoExecute
        operator: Exists
    nodeSelector:
      node-role.kubernetes.io/master: ""
  serviceConfiguration:
    adminUsername: "admin"
    adminPassword: "contrail123"

