---
apiVersion: contrail.juniper.net/v1alpha1
kind: Manager
metadata:
  name: cluster1
  namespace: contrail
spec:
  commonConfiguration:
    hostNetwork: true
    replicas: 1
  services:
    cassandras:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: cassandra1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          containers:
            cassandra:
              image: cassandra:3.11.4
            init:
              image: python:3.8.2-alpine
            init2:
              image: cassandra:3.11.4
    config:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: config1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
            analyticsapi:
              image: opencontrailnightly/contrail-analytics-api:1910-latest
            api:
              image: opencontrailnightly/contrail-controller-config-api:1910-latest
            collector:
              image: opencontrailnightly/contrail-analytics-collector:1910-latest
            devicemanager:
              image: opencontrailnightly/contrail-controller-config-devicemgr:1910-latest
            dnsmasq:
              image: opencontrailnightly/contrail-external-dnsmasq:1910-latest
            init:
              image: python:3.8.2-alpine
            init2:
              image: busybox:1.31
            nodeinit:
              image: opencontrailnightly/contrail-node-init:1910-latest
            redis:
              image: redis:4.0.2
            schematransformer:
              image: opencontrailnightly/contrail-controller-config-schema:1910-latest
            servicemonitor:
              image: opencontrailnightly/contrail-controller-config-svcmonitor:1910-latest
            queryengine:
              image: opencontrailnightly/contrail-analytics-query-engine:1910-latest
          logLevel: SYS_DEBUG
          zookeeperInstance: zookeeper1
    controls:
    - metadata:
        labels:
          contrail_cluster: cluster1
          control_role: master
        name: control1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
            control:
              image: opencontrailnightly/contrail-controller-control-control:1910-latest
            dns:
              image: opencontrailnightly/contrail-controller-control-dns:1910-latest
            init:
              image: python:3.8.2-alpine
            named:
              image: opencontrailnightly/contrail-controller-control-named:1910-latest
            nodeinit:
              image: opencontrailnightly/contrail-node-init:1910-latest
            statusmonitor:
              image: kaweue/contrail-statusmonitor:debug
          zookeeperInstance: zookeeper1
    kubemanagers:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: kubemanager1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
            init:
              image: python:3.8.2-alpine
            kubemanager:
              image: michaelhenkel/contrail-kubernetes-kube-manager:1910-latest
            nodeinit:
              image: opencontrailnightly/contrail-node-init:1910-latest
          ipFabricForwarding: false
          ipFabricSnat: true
          kubernetesTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
          useKubeadmConfig: true
          zookeeperInstance: zookeeper1
    provisionManager:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: provmanager1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
          replicas: 1
        serviceConfiguration:
          containers:
            init:
              image: python:3.8.2-alpine
            provisioner:
              image: kaweue/contrail-provisioner:master.1175
    rabbitmq:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: rabbitmq1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          containers:
            init:
              image: python:3.8.2-alpine
            rabbitmq:
              image: rabbitmq:3.7.16
    vrouters:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: vroutermaster
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
            init:
              image: python:3.8.2-alpine
            nodeinit:
              image: opencontrailnightly/contrail-node-init:1910-latest
            nodemanager:
              image: opencontrailnightly/contrail-nodemgr:1910-latest
            vrouteragent:
              image: opencontrailnightly/contrail-vrouter-agent:1910-latest
            vroutercni:
              image: michaelhenkel/contrailcni:v0.0.1
            vrouterkernelbuildinit:
              image: opencontrailnightly/contrail-vrouter-kernel-build-init:1910-latest
            vrouterkernelinit:
              image: opencontrailnightly/contrail-vrouter-kernel-init:1910-latest
          controlInstance: control1
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: vrouternodes
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.opencontrail.org: vrouter
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
            init:
              image: python:3.8.2-alpine
            nodeinit:
              image: opencontrailnightly/contrail-node-init:1910-latest
            nodemanager:
              image: opencontrailnightly/contrail-nodemgr:1910-latest
            vrouteragent:
              image: opencontrailnightly/contrail-vrouter-agent:1910-latest
            vroutercni:
              image: michaelhenkel/contrailcni:v0.0.1
            vrouterkernelbuildinit:
              image: opencontrailnightly/contrail-vrouter-kernel-build-init:1910-latest
            vrouterkernelinit:
              image: opencontrailnightly/contrail-vrouter-kernel-init:1910-latest
          controlInstance: control1
    webui:
      metadata:
        labels:
          contrail_cluster: cluster1
        name: webui1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          cassandraInstance: cassandra1
          containers:
            init:
              image: python:3.8.2-alpine
            nodeinit:
              image: opencontrailnightly/contrail-node-init:1910-latest
            redis:
              image: redis:4.0.2
            webuijob:
              image: opencontrailnightly/contrail-controller-webui-job:1910-latest
            webuiweb:
              image: opencontrailnightly/contrail-controller-webui-web:1910-latest
    zookeepers:
    - metadata:
        labels:
          contrail_cluster: cluster1
        name: zookeeper1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          containers:
            init:
              image: python:3.8.2-alpine
            zookeeper:
              image: docker.io/zookeeper:3.5.5
