---
apiVersion: contrail.juniper.net/v1alpha1
kind: Manager
metadata:
  name: cluster1
spec:
  commonConfiguration:
    replicas: 3
    hostNetwork: true
    imagePullSecrets:
    - contrail-nightly
  services:
    cassandras:
    - metadata:
        name: cassandra1
        labels:
          contrail_cluster: cluster1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          images:
            cassandra: cassandra:3.11.4
            init: python:3.8.2-alpine
    zookeepers:
    - metadata:
        name: zookeeper1
        labels:
          contrail_cluster: cluster1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          images:
            zookeeper: docker.io/zookeeper:3.5.4
            init: python:3.8.2-alpine
    rabbitmq:
      metadata:
        name: rabbitmq1
        labels:
          contrail_cluster: cluster1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          images:
            rabbitmq: rabbitmq:3.7.16
            init: python:3.8.2-alpine
    config:
      metadata:
        name: config1
        labels:
          contrail_cluster: cluster1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          cassandraInstance: cassandra1
          zookeeperInstance: zookeeper1
          images:
            api: hub.juniper.net/contrail-nightly/contrail-controller-config-api:1908.47
            devicemanager: hub.juniper.net/contrail-nightly/contrail-controller-config-devicemgr:1908.47
            schematransformer: hub.juniper.net/contrail-nightly/contrail-controller-config-schema:1908.47
            servicemonitor: hub.juniper.net/contrail-nightly/contrail-controller-config-svcmonitor:1908.47
            analyticsapi: hub.juniper.net/contrail-nightly/contrail-analytics-api:1908.47
            collector: hub.juniper.net/contrail-nightly/contrail-analytics-collector:1908.47
            redis: redis:4.0.2
            nodemanagerconfig: hub.juniper.net/contrail-nightly/contrail-nodemgr:1908.47
            nodemanageranalytics: hub.juniper.net/contrail-nightly/contrail-nodemgr:1908.47
            nodeinit: hub.juniper.net/contrail-nightly/contrail-node-init:1908.47
            init: python:3.8.2-alpine
    kubemanagers:
    - metadata:
        name: kubemanager1
        labels:
          contrail_cluster: cluster1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          cassandraInstance: cassandra1
          zookeeperInstance: zookeeper1
          images:
            kubemanager: hub.juniper.net/contrail-nightly/contrail-kubernetes-kube-manager:1908.47
            nodeinit: hub.juniper.net/contrail-nightly/contrail-node-init:1908.47
            init: python:3.8.2-alpine
          useKubeadmConfig: true
          #serviceAccount: contrail-service-account
          #clusterRole: contrail-cluster-role
          #clusterRoleBinding: contrail-cluster-role-binding
          #cloudOrchestrator: kubernetes
          #kubernetesAPIServer: "10.96.0.1"
          #kubernetesAPIPort: 443
          #podSubnet: 10.32.0.0/12
          #serviceSubnet: 10.96.0.0/12
          #kubernetesClusterName: kubernetes
          ipFabricForwarding: true
          ipFabricSnat: true
          kubernetesTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    controls:
    - metadata:
        name: control1
        labels:
          contrail_cluster: cluster1
          control_role: master
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          cassandraInstance: cassandra1
          zookeeperInstance: zookeeper1
          images:
            control: hub.juniper.net/contrail-nightly/contrail-controller-control-control:1908.47
            dns: hub.juniper.net/contrail-nightly/contrail-controller-control-dns:1908.47
            named: hub.juniper.net/contrail-nightly/contrail-controller-control-named:1908.47
            nodemanager: hub.juniper.net/contrail-nightly/contrail-nodemgr:1908.47
            nodeinit: hub.juniper.net/contrail-nightly/contrail-node-init:1908.47
            init: python:3.8.2-alpine
    webui:
      metadata:
        name: webui1
        labels:
          contrail_cluster: cluster1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          cassandraInstance: cassandra1
          images:
            webuiweb: hub.juniper.net/contrail-nightly/contrail-controller-webui-web:1908.47
            webuijob: hub.juniper.net/contrail-nightly/contrail-controller-webui-job:1908.47
            redis: redis:4.0.2
            nodeinit: hub.juniper.net/contrail-nightly/contrail-node-init:1908.47
    vrouters:
    - metadata:
        name: vroutermaster
        labels:
          contrail_cluster: cluster1
      spec:
        commonConfiguration:
          create: false
          nodeSelector:
            node-role.kubernetes.io/master: ""
        serviceConfiguration:
          cassandraInstance: cassandra1
          controlInstance: control1
          images:
            vrouteragent: hub.juniper.net/contrail-nightly/contrail-vrouter-agent:1908.47
            vrouterkernelinit: michaelhenkel/contrail-vrouter-kernel-init:1909.30
            vroutercni: hub.juniper.net/contrail-nightly/contrail-kubernetes-cni-init:1908.47
            nodemanager: hub.juniper.net/contrail-nightly/contrail-nodemgr:1908.47
            nodeinit: hub.juniper.net/contrail-nightly/contrail-node-init:1908.47
            init: python:3.8.2-alpine
    - metadata:
        name: vrouternodes
        labels:
          contrail_cluster: cluster1
      spec:
        commonConfiguration:
          create: true
          nodeSelector:
            node-role.opencontrail.org: "vrouter"
        serviceConfiguration:
          cassandraInstance: cassandra1
          controlInstance: control1
          images:
            vrouteragent: hub.juniper.net/contrail-nightly/contrail-vrouter-agent:1908.47
            vrouterkernelinit: michaelhenkel/contrail-vrouter-kernel-init:1909.30
            vroutercni: hub.juniper.net/contrail-nightly/contrail-kubernetes-cni-init:1908.47
            nodemanager: hub.juniper.net/contrail-nightly/contrail-nodemgr:1908.47
            nodeinit: hub.juniper.net/contrail-nightly/contrail-node-init:1908.47
            init: python:3.8.2-alpine
